CREATE TABLE build_trigger
(
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type                   VARCHAR(255) NOT NULL,
  next_execution_time    TIMESTAMP WITH TIME ZONE,
  created                TIMESTAMP WITH TIME ZONE NOT NULL,
  updated                TIMESTAMP WITH TIME ZONE NOT NULL,
  repository_data        TEXT NOT NULL,
  scheduled_trigger_data TEXT,
  vcs_trigger_data       TEXT
);
COMMENT ON TABLE build_trigger IS 'Данные триггера сборок';
COMMENT ON COLUMN build_trigger.id IS 'Уникальный автоинкрементный идентификатор триггера';
COMMENT ON COLUMN build_trigger.type IS 'Тип триггера';
COMMENT ON COLUMN build_trigger.next_execution_time IS 'Время следующего исполнения триггера';
COMMENT ON COLUMN build_trigger.created IS 'Дата создания триггера';
COMMENT ON COLUMN build_trigger.updated IS 'Дата обновления триггера';
COMMENT ON COLUMN build_trigger.repository_data IS 'Данные о репозитории, для которого собираются сборки';
COMMENT ON COLUMN build_trigger.scheduled_trigger_data IS 'Данные о триггере, выполняющемуся по расписанию';
COMMENT ON COLUMN build_trigger.vcs_trigger_data IS 'Данные о триггере, выполняющемуся по событию в VCS';

CREATE INDEX IF NOT EXISTS build_trigger_next_execution_time_idx ON build_trigger(next_execution_time);