CREATE TABLE branch
(
    branch_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name   VARCHAR(255) NOT NULL,
    latest_commit VARCHAR(255),
    trigger_id    BIGINT CONSTRAINT branch_trigger_fk REFERENCES build_trigger ON DELETE CASCADE
);

COMMENT ON TABLE branch IS 'Данные о ветке репозитория';
COMMENT ON COLUMN branch.branch_id IS 'Уникальный автоинкрементный идентификатор ветки';
COMMENT ON COLUMN branch.branch_name IS 'Наименование ветки';
COMMENT ON COLUMN branch.latest_commit IS 'Последний коммит ветки';
COMMENT ON COLUMN branch.trigger_id IS 'Идентификатор триггера, к которому относится ветка';
